name: BuildPackage
on:
  workflow_dispatch:
  workflow_call:
jobs:
    build-package:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.9
          uses: actions/setup-python@v3
          with:
              python-version: 3.9
        - name: Build pip package
          run: |
              pip install -U pip build
              python3 -m build --sdist --wheel --outdir dist/ .
        - name: Archive PyPI package
          uses: actions/upload-artifact@v3
          with:
              name: pip-package
              path: dist/*
    deploy-package:
      if: startsWith(github.ref, 'refs/tags')
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        - name: download artifact
          uses: actions/download-artifact@v3
        - name: list packages
          run: find ./*package*
        - name: Publish package
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}
            packages_dir: pip-package/